### PR TITLE
Extend new APB defines in integration document

### PR DESCRIPTION
**Pull request by steven-bellock**
Follow-up to #279.

Signed-off-by: Steven Bellock <sbellock@nvidia.com>

### CODE REVIEW

**Comment by steven-bellock** [comment]
@Nitsirks now that I look at this, why is `CALIPTRA_APB_DATA_WIDTH` configurable by the Integrator? This should be an unconfigurable 32-bits.

**Comment by Nitsirks** [comment]
You are right - it's probably best if none of the APB parameters are configurable.

I think early on these got put in this list, but we never tested them and there is no reason for them to be configurable. Integrators should put a gasket here to comply with the caliptra settings.

**Review by steph-morton — DISMISSED** [review]

**Comment by andreslagarcavilla** [comment]
Unclear if this is ready for merge

**Comment by steven-bellock** [comment]
> Unclear if this is ready for merge

No, I'll need to revise it.

**Comment by steven-bellock** [comment]
@calebofearth @Nitsirks I deleted APB from Table 3 but I think it's fine to have the macro name in the Width column, especially since Table 8 uses them.

**Review by steph-morton — APPROVED** [review]

**Review by calebofearth — APPROVED** [review]

**Pull request merged**
