### PR TITLE
Add Register docs links to README.md

### PR DESCRIPTION
**Pull request by andreslagarcavilla**
Also fix a couple formatting nits

### CODE REVIEW

**Review by mcockrell-google — APPROVED** [review]

**Comment by andreslagarcavilla** [comment]
Bharat should we send this to goog-dev instead?

**Comment by bharatpillilli** [comment]
Yes @andreslagarcavilla - that wld be great - @howardtr - can you please help as needed here?

**Comment by andreslagarcavilla** [comment]
Ima go ahead create dev-goog from current dev-msft unless I hear objections

**Comment by andreslagarcavilla** [comment]
Rebased to dev-goog, this PR has approvals. Go team go.

**Comment by andreslagarcavilla** [comment]
done through PR #13 , closing this one

**Pull request closed without merging**
