### PR TITLE
Additional round of lint cleanup

### PR DESCRIPTION
**Pull request by Nitsirks**
removed lint blackboxes
enabled TRNG files during lint runs
cleaned use of structs that violate unpacked struct usage
cast width of dynamic shifts to make lint happy
casting some arithmetic widths, math parameter widths
fixed enum ints to enum sized logic

### CODE REVIEW

**Comment by mojtaba-bisheh** [comment]
Does it merge with main? since LMS is in the main already but this PR does not include it

**Comment by Nitsirks** [comment]
> Does it merge with main? since LMS is in the main already but this PR does not include it

I have merged with main and I am running lint on that now. Will update shortly.

**Comment by calebofearth** [comment]
@amullick007 @nstewart-amd

**Comment by amullick007** [comment]
> @amullick007 @nstewart-amd

Spyglass Lint is clean on this PR

**Review by calebofearth — APPROVED** [review]

**Comment by calebofearth** [comment]
> > @amullick007 @nstewart-amd
> 
> Spyglass Lint is clean on this PR

Excellent. Can you approve the PR so we can get it merged?

**Comment by amullick007** [comment]
> > > @amullick007 @nstewart-amd
> > 
> > 
> > Spyglass Lint is clean on this PR
> 
> Excellent. Can you approve the PR so we can get it merged?

Can you please add me as a reviewer to this PR?

**Comment by calebofearth** [comment]
> > > > @amullick007 @nstewart-amd
> > > 
> > > 
> > > Spyglass Lint is clean on this PR
> > 
> > 
> > Excellent. Can you approve the PR so we can get it merged?
> 
> Can you please add me as a reviewer to this PR?

I am unable to add you for some reason, when I try to add your username I see this:
image
Perhaps you're not a member of the Caliptra team on this GitHub org?

**Review by upadhyayulakiran — APPROVED** [review]

**Pull request merged**
