### PR TITLE
Rename Caliptra_rtl.md → CaliptraIntegrationSpecification.md

### PR DESCRIPTION
**Pull request by andreslagarcavilla**
Matching PR for main repo incoming as well

### CODE REVIEW

**Comment by fdamato** [comment]
In general, I`m not opposed to this change, but I have few thoughts I would like to share.

While it sounds very logical to have the HW Release spec as part of the HW repo, I think it will have some downsides.
1) It would reduce its visibility from external integrators, who are not involved too much into the HW/SW contribution.
2) Considering that nightly release come from the SW repo, and the milestone releases from the Spec Repo, having the spec into the HW repo, might further increase the fragmentation of the deliverable vs spec.

**Comment by andreslagarcavilla** [comment]
ok, will reshuffle

**Comment by andreslagarcavilla** [comment]
Now a single commit for camel case

**Review by FerralCoder — APPROVED** [review]

**Review by steph-morton — APPROVED** [review]

**Review by fdamato — APPROVED** [review]

**Review by calebofearth — COMMENTED** [review]
@mcockrell-google suggested we rename this document to CaliptraIntegrationGuide - I think there are arguments for either convention:
- `Specification`: This document provides inviolable rules regarding interfaces, protocols, fuse protection, etc.
- `Guide`: This document is not providing any architectural design rules, but simply conveying information about the design as necessary to allow integrators to successfully add the IP.

Matt, did you have any additional motivations for that request?

**Comment by mcockrell-google** [comment]
No, I just wanted something to help guide anyone looking to integrate. Caliptra_rtl seemed a bit misleading.

**Review by calebofearth — APPROVED** [review]

**Pull request merged**
