### PR TITLE
Merge dev-msft into dev-integrate.

### PR DESCRIPTION
**Pull request by anjpar**

### CODE REVIEW

**Comment by howardtr** [comment]
Not sure if you were planning on doing a merge from dev-goog after, but can we get the verilator smoke test updates at least?

https://github.com/chipsalliance/caliptra-rtl/blob/dev-goog/.github/workflows/build-test-verilator.yml

**Comment by andreslagarcavilla** [comment]
We're still missing a pile of commits from other contributors

$ git log --pretty=format:"%ad %h %s %an" --date=short upstream/dev-integrate..upstream/dev-goog
2023-05-05 57a716b Adding check for "TESTCASE PASSED" string at the end of CI test (#81) Howard T
2023-05-04 bd79b88 Moving tool installation to step prior to matrix generation (#70) Howard T
2023-04-26 94b0d14 Adding csrng.cmd_req fields (#74) Howard T
2023-04-24 721cf11 Dynamic generation of the CI test matrix (#52) Maciej Kurc
2023-04-04 15640e7 Fix qspi tie off at top level.  Only tie off when define is not set. Howard Tran
2023-04-04 ad387f9 Merge branch 'dev-msft' into dev-goog Howard Tran
2023-03-29 fbdba65 Fix ifdef for UART assertion error Howard Tran
2023-03-28 1e1f252 Integrate UART into top level (#41) Howard T
2023-03-23 a5fb21b Adding el2_param_t to el2_pkg in riscv_core (#35) Howard T
2023-03-21 8809ddb Update compile.yml +.vf with new files added in prim (#30) Howard T
2023-03-21 824ab00 Adding QSPI into top level  (#28) Howard T
2023-03-21 aa66009 Update Verilator to 5.002 (#29) Howard T
2023-03-17 9884242 Adding spi_host IP and unit test (#17) Howard T

**Comment by andreslagarcavilla** [comment]
Tests are failing to boot ROM

  1,196,539 UART: ROM Error: 0x90040001 (SignatureGenerateFailure)

**Comment by calebofearth** [comment]
> We're still missing a pile of commits from other contributors
> 
> $ git log --pretty=format:"%ad %h %s %an" --date=short upstream/dev-integrate..upstream/dev-goog 2023-05-05 [57a716b](https://github.com/chipsalliance/caliptra-rtl/commit/57a716bf4b66c2cc9d854fd97f12eac8b238b821) Adding check for "TESTCASE PASSED" string at the end of CI test (#81) Howard T 2023-05-04 [bd79b88](https://github.com/chipsalliance/caliptra-rtl/commit/bd79b88789f945225f19884ceb8d5913092fea59) Moving tool installation to step prior to matrix generation (#70) Howard T 2023-04-26 [94b0d14](https://github.com/chipsalliance/caliptra-rtl/commit/94b0d1497793aec0e13399f4e70e1d2f13bed0ad) Adding csrng.cmd_req fields (#74) Howard T 2023-04-24 [721cf11](https://github.com/chipsalliance/caliptra-rtl/commit/721cf1171b765533602bbadb9cc94b5f1da480ab) Dynamic generation of the CI test matrix (#52) Maciej Kurc 2023-04-04 [15640e7](https://github.com/chipsalliance/caliptra-rtl/commit/15640e7ac8a613325d543e56fc35bb033fbfa01c) Fix qspi tie off at top level. Only tie off when define is not set. Howard Tran 2023-04-04 [ad387f9](https://github.com/chipsalliance/caliptra-rtl/commit/ad387f9c5f8be415534d806e066fb476974ab609) Merge branch 'dev-msft' into dev-goog Howard Tran 2023-03-29 [fbdba65](https://github.com/chipsalliance/caliptra-rtl/commit/fbdba65d3ce1f5295580062ce4b5e9d9995165e3) Fix ifdef for UART assertion error Howard Tran 2023-03-28 [1e1f252](https://github.com/chipsalliance/caliptra-rtl/commit/1e1f252f6b5fd3349b944c94464494481b3ac182) Integrate UART into top level (#41) Howard T 2023-03-23 [a5fb21b](https://github.com/chipsalliance/caliptra-rtl/commit/a5fb21b3fde3e2f6c03e1a640e29b9a0bade7339) Adding el2_param_t to el2_pkg in riscv_core (#35) Howard T 2023-03-21 [8809ddb](https://github.com/chipsalliance/caliptra-rtl/commit/8809ddb3cf936224062d71484f6202ccb3bdb5bb) Update compile.yml +.vf with new files added in prim (#30) Howard T 2023-03-21 [824ab00](https://github.com/chipsalliance/caliptra-rtl/commit/824ab0068452459cf54b30aa5c291fd8a01a9803) Adding QSPI into top level (#28) Howard T 2023-03-21 [aa66009](https://github.com/chipsalliance/caliptra-rtl/commit/aa6600911adf9f6c3aa113b0bf81a037874a7983) Update Verilator to 5.002 (#29) Howard T 2023-03-17 [9884242](https://github.com/chipsalliance/caliptra-rtl/commit/9884242add658f6d076984c882be1aa54de772d9) Adding spi_host IP and unit test (#17) Howard T

This should be resolved here: https://github.com/chipsalliance/caliptra-rtl/pull/86

**Pull request merged**
