### PR TITLE
Dev msft 20231102

### PR DESCRIPTION
**Pull request by calebofearth**
This Pull Request is of value for the 1.0 release due to improved clarity in the documentation of interrupt trigger registers.

### CODE REVIEW

**Comment by andreslagarcavilla** [comment]
Hi can you add the two (silly, simple) .md move PRs? #272 and #274 . Thanks

**Comment by andreslagarcavilla** [comment]
Or you can elide those if you're fine to merge with `main` after all is said and done

**Comment by calebofearth** [comment]
> Or you can elide those if you're fine to merge with `main` after all is said and done

This makes the most sense. This PR is headed towards dev-msft, with the final intent to merge into main. We'll reintegrate main to dev-msft at the end of the sync, and get this doc change at that time.

**Comment by andreslagarcavilla** [comment]
Sounds good. It's your branch -- you don't need me to review it :)

**Review by Nitsirks — APPROVED** [review]

**Pull request merged**
