### PR TITLE
Exclude some CI tests for Verilator

### PR DESCRIPTION
**Pull request by mkurc-ant**
This PR adds a mechanism for excluding specific CI tests. The list needs to be passed via the `EXCLUDE_TESTS` env variable to the job that builds CI test matrix. Solves https://github.com/chipsalliance/caliptra-rtl/issues/126

Currently the PR has no effect on the CI as the excluded tests are not yet integrated

### CODE REVIEW

**Comment by howardtr** [comment]
@calebofearth - do you want this to go through dev-goog?

**Comment by calebofearth** [comment]
> @calebofearth - do you want this to go through dev-goog?

Let's submit against `dev-msft`. `dev-msft` will be the first point of contact once we sync in those excluded smoke tests.

**Review by calebofearth — APPROVED** [review]
Thanks @mkurc-ant this change looks great!

**Review by howardtr — APPROVED** [review]
let's repoint to dev-msft as caleb mentioned, thanks!

**Review by upadhyayulakiran — APPROVED** [review]

**Comment by calebofearth** [comment]
> let's repoint to dev-msft as caleb mentioned, thanks!

I went ahead and changed the merge target to `dev-msft`. Thanks all!

**Pull request merged**
